FROM node:8-alpine

LABEL io.cadvisor.metric.prometheus-http="/etc/custom-metrics/definition.json"

ENV NODE_ENV production
# this will enable polling, hot-reload will work on docker or network volumes
ENV CHOKIDAR_USEPOLLING true

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./ /usr/src/app

RUN npm install

EXPOSE 8080
EXPOSE 9876

CMD [ "npm", "run", "start" ]
